# Creating Arrays

- arange()
- linspace()
- array()
- zeros()
- ones()
- identity()

In [1]:
import numpy as np

### arange(start, stop, gap)

In [2]:
a = np.arange(4)

In [3]:
a

array([0, 1, 2, 3])

In [4]:
b = np.arange(1,10,2)

In [5]:
b

array([1, 3, 5, 7, 9])

### ones and zeros

> **ones(shape, dtype='float64')**

In [6]:
c = np.ones((2,3), dtype='int32')

In [7]:
c

array([[1, 1, 1],
       [1, 1, 1]])

In [8]:
d = np.zeros((3,3), dtype='int32')
d

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

### Identity
- Generate an **n** by **n** identity array. The default dtype is float64.

In [11]:
a = np.identity(4, dtype='int32')

In [12]:
a

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]])

### Linspace

- Generate **N** evenly spaced elements between (and including) start and stop values

In [13]:
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])