# Array Operations

In [2]:
import numpy as np

### Simple Array Math

In [3]:
a = np.array([1,2,3,4])
b = np.array([2,3,4,5])

In [6]:
a+b

array([3, 5, 7, 9])

In [7]:
a*b

array([ 2,  6, 12, 20])

### Math Functions

In [8]:
x = np.arange(11)

In [9]:
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [12]:
c = (2 * np.pi) / 10

In [13]:
c

0.6283185307179586

In [14]:
c * x

array([0.        , 0.62831853, 1.25663706, 1.88495559, 2.51327412,
       3.14159265, 3.76991118, 4.39822972, 5.02654825, 5.65486678,
       6.28318531])

In [15]:
y = np.sin(x)

In [16]:
y

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849,
       -0.54402111])