# Setting Array Elements

In [11]:
import numpy as np

### Array Indexing

In [14]:
a = np.array([0,1,2,3])

![Array Indexing](Images/1.png)

In [16]:
a[0]
a[2]

2

In [17]:
a[0] = 10
a

array([10,  1,  2,  3])

![Array Indexing](Images/2.png)

### Beware of Type

In [6]:
a.dtype

dtype('int32')

> assigning a float into an in32 array truncates the decimal

In [7]:
a[0] = 10.6

In [8]:
a

array([10,  1,  2,  3])

#### fill works the same way

In [9]:
a.fill(-4.8)

In [10]:
a

array([-4, -4, -4, -4])