# Multidimensional Array

In [1]:
import numpy as np

### Creating Multi Dimensional Arrays

In [2]:
a = np.array([[0,1,2,3],
             [10,11,12,13]])

In [3]:
a

array([[ 0,  1,  2,  3],
       [10, 11, 12, 13]])

![2-D Array](Images/3.png)

### Shape = (Rows, Columns)

In [4]:
a.shape

(2, 4)

![2-D Array](Images/4.png)

### Element Count

In [5]:
a.size

8

![2-D Array](Images/5.png)

### Get / Set Elements

In [6]:
a[1,3]

13

![Get-Set Limit](Images/6.png)

In [7]:
a[1, 3] = -1

In [8]:
a

array([[ 0,  1,  2,  3],
       [10, 11, 12, -1]])

![get-set](Images/7.png)

### Address Second (Oneth) Row using Single Index

In [9]:
a[1]

array([10, 11, 12, -1])