# Slicing

In [1]:
import numpy as np

> ### var[lower:upper:step]

- Extracts a portion of a Sequence by specifying a lower and upper bound.
- The lower bound element is inluded, but the upper bound element is **not** included


### Slicing Arrays

            -5,-4,-3,-2,-1
             0, 1, 2, 3, 4

In [3]:
a = np.array([10,11,12,13,14])
a

array([10, 11, 12, 13, 14])

[10, **11, 12**, 13, 14]

In [6]:
a[1:3]

array([11, 12])

*negetive indices work also*

In [7]:
a[1:-2]

array([11, 12])

### Omiting Indices

In [8]:
a = np.array([10,11,12,13,14])
a

array([10, 11, 12, 13, 14])

- **grab first three elements**

In [9]:
a[:3]

array([10, 11, 12])

- **grab last two elements**

In [10]:
a[-2:]

array([13, 14])

- **every other element**

In [11]:
a[::2]

array([10, 12, 14])