# Slices are References

##### Slices are references to locations in memory. These memory locations can be used in assignment operations.
<hr>

In [1]:
import numpy as np

In [2]:
a = np.array([0,1,2,3,4])

### Slicing last two elements returns the data there

In [3]:
a[-2:]

array([3, 4])

### We can insert an iterable of length two

In [4]:
a[-2:] = [-1,-2]

In [5]:
a

array([ 0,  1,  2, -1, -2])

#### or a scalar value

In [6]:
a[-2:] = 99

In [7]:
a

array([ 0,  1,  2, 99, 99])