# Excercise - Array Slicing

In [6]:
import numpy as np

![Array Slicing](Images/8.png)

In [7]:
a = np.arange(25).reshape(5,5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

#### Red

In [8]:
a[:,1::2]

array([[ 1,  3],
       [ 6,  8],
       [11, 13],
       [16, 18],
       [21, 23]])

#### Blue

In [11]:
a[1::2, :-1:2]

array([[ 5,  7],
       [15, 17]])

#### Yellow

In [12]:
a[4]

array([20, 21, 22, 23, 24])

In [13]:
a[-1,:]

array([20, 21, 22, 23, 24])